In [1]:
import numpy as np

In [19]:
a = [3,5,6,78,8,9]
a = np.array`(a,dtype = float,ndmin = 2)

In [15]:
b = np.array([3,5,6,78,8,9])

In [12]:
b[1]

np.int64(5)

In [20]:
a

array([[ 3.,  5.,  6., 78.,  8.,  9.]])

In [40]:
m_list_1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
My_list = np.array(m_list_1)

In [24]:
My_list*10

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [26]:
# You can also create arrays by defining the start value,
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.linspace(0,2,100)

array([0.        , 0.02020202, 0.04040404, 0.06060606, 0.08080808,
       0.1010101 , 0.12121212, 0.14141414, 0.16161616, 0.18181818,
       0.2020202 , 0.22222222, 0.24242424, 0.26262626, 0.28282828,
       0.3030303 , 0.32323232, 0.34343434, 0.36363636, 0.38383838,
       0.4040404 , 0.42424242, 0.44444444, 0.46464646, 0.48484848,
       0.50505051, 0.52525253, 0.54545455, 0.56565657, 0.58585859,
       0.60606061, 0.62626263, 0.64646465, 0.66666667, 0.68686869,
       0.70707071, 0.72727273, 0.74747475, 0.76767677, 0.78787879,
       0.80808081, 0.82828283, 0.84848485, 0.86868687, 0.88888889,
       0.90909091, 0.92929293, 0.94949495, 0.96969697, 0.98989899,
       1.01010101, 1.03030303, 1.05050505, 1.07070707, 1.09090909,
       1.11111111, 1.13131313, 1.15151515, 1.17171717, 1.19191919,
       1.21212121, 1.23232323, 1.25252525, 1.27272727, 1.29292929,
       1.31313131, 1.33333333, 1.35353535, 1.37373737, 1.39393939,
       1.41414141, 1.43434343, 1.45454545, 1.47474747, 1.49494

In [31]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
My_array = My_list

In [35]:
My_array.size

9

In [37]:
len(My_array)

3

In [38]:
My_array.shape

(3, 3)

In [41]:
My_array.dtype

dtype('int64')

# Data Types
# Boolean : np.bool_
# Char : np.byte
# Short : np.short
# Integer : np.short
# Long : np.int_
# Float : np.single & np.float32
# Double : np.double & np.float64
# np.int8 : -128 to 127
# np.int16 : -32768 to 32767
# np.int32 : -2147483648 to 2147483647
# np.int64 : -9223372036854775808 to 9223372036854775807

In [74]:
my_arr2 = np.random.randint(1,500, size = (3,3), dtype= np.int16)

In [100]:
my_arr3 = np.random.choice([1,2,3,4,5,6],size=(10,10),replace=True)
my_arr3

array([[4, 5, 5, 6, 2, 5, 3, 4, 1, 6],
       [4, 3, 6, 4, 5, 5, 2, 5, 1, 5],
       [1, 4, 4, 5, 3, 1, 2, 3, 4, 6],
       [6, 6, 2, 4, 2, 4, 5, 5, 2, 5],
       [1, 5, 1, 3, 1, 3, 6, 2, 2, 1],
       [4, 3, 6, 3, 1, 2, 4, 1, 1, 1],
       [5, 2, 2, 2, 6, 5, 5, 5, 2, 2],
       [6, 1, 1, 6, 6, 1, 2, 3, 4, 5],
       [2, 2, 5, 3, 5, 6, 4, 2, 4, 4],
       [5, 6, 5, 5, 5, 1, 6, 4, 5, 6]])

In [75]:
print(my_arr2)

[[302 396 418]
 [286 335 409]
 [120 288 177]]


In [86]:
my_arr2[1,1]

my_arr2.item(2,2)

177

In [95]:
# Slicing

my_arr2[::-1,::-1]
my_arr2[(my_arr2%2 == 0) & (my_arr2>400)]

array([418], dtype=int16)

In [101]:
np.unique(my_arr3)

array([1, 2, 3, 4, 5, 6])

In [102]:
np.unique_counts(my_arr3)

UniqueCountsResult(values=array([1, 2, 3, 4, 5, 6]), counts=array([16, 18, 10, 16, 24, 16]))

In [103]:
print(my_arr3)

[[4 5 5 6 2 5 3 4 1 6]
 [4 3 6 4 5 5 2 5 1 5]
 [1 4 4 5 3 1 2 3 4 6]
 [6 6 2 4 2 4 5 5 2 5]
 [1 5 1 3 1 3 6 2 2 1]
 [4 3 6 3 1 2 4 1 1 1]
 [5 2 2 2 6 5 5 5 2 2]
 [6 1 1 6 6 1 2 3 4 5]
 [2 2 5 3 5 6 4 2 4 4]
 [5 6 5 5 5 1 6 4 5 6]]


In [106]:
#Reshape Array

my_arr3.reshape((50,2))

array([[4, 5],
       [5, 6],
       [2, 5],
       [3, 4],
       [1, 6],
       [4, 3],
       [6, 4],
       [5, 5],
       [2, 5],
       [1, 5],
       [1, 4],
       [4, 5],
       [3, 1],
       [2, 3],
       [4, 6],
       [6, 6],
       [2, 4],
       [2, 4],
       [5, 5],
       [2, 5],
       [1, 5],
       [1, 3],
       [1, 3],
       [6, 2],
       [2, 1],
       [4, 3],
       [6, 3],
       [1, 2],
       [4, 1],
       [1, 1],
       [5, 2],
       [2, 2],
       [6, 5],
       [5, 5],
       [2, 2],
       [6, 1],
       [1, 6],
       [6, 1],
       [2, 3],
       [4, 5],
       [2, 2],
       [5, 3],
       [5, 6],
       [4, 2],
       [4, 4],
       [5, 6],
       [5, 5],
       [5, 1],
       [6, 4],
       [5, 6]])

In [16]:
my_arr_3 = np.arange(5,10)

In [17]:
my_arr_3

array([5, 6, 7, 8, 9])

In [18]:
my_arr_3[:5:-2]

array([], dtype=int64)

In [20]:
my_arr_3[[2,4]] = [50,10]

In [22]:
np.take(my_arr_3,[2,4])

array([50, 10])

In [23]:
np.put(my_arr_3,[2,4],[11,12])

In [24]:
my_arr_3

array([ 5,  6, 11,  8, 12])

In [27]:
my_arr_4 = np.random.randint(200,size = (4,4))

In [28]:
my_arr_4

array([[197,  54,  90,  54],
       [ 27,  37, 148,  98],
       [198, 106, 182,  92],
       [162, 166, 154, 156]], dtype=int32)

In [39]:
my_arr_4.reshape((1,-1))

array([[197,  54,  90,  54,  27,  37, 148,  98, 198, 106, 182,  92, 162,
        166, 154, 156]], dtype=int32)

In [154]:
array = np.random.randint(200,size = (4,4))

In [155]:
my_arr_4

array([[197,  54],
       [ 90,  54],
       [ 27,  37],
       [148,  98],
       [198, 106],
       [182,  92],
       [162, 166],
       [154, 156]], dtype=int32)

In [48]:
array.resize((5,5))

In [68]:
array

array([[156, 112,  89, 110],
       [188,  69, 151, 139],
       [ 97, 122, 183,  67],
       [ 55, 137,  38, 151]], dtype=int32)

In [50]:
array.transpose()

array([[156, 168,  88,  78,   0],
       [ 96, 100,  42,   0,   0],
       [174,  36,  88,   0,   0],
       [151,  64, 169,   0,   0],
       [ 11,  20, 191,   0,   0]], dtype=int32)

In [52]:
array.swapaxes(1,0)

array([[156, 168,  88,  78,   0],
       [ 96, 100,  42,   0,   0],
       [174,  36,  88,   0,   0],
       [151,  64, 169,   0,   0],
       [ 11,  20, 191,   0,   0]], dtype=int32)

In [56]:
array.flatten('F')

array([156, 168,  88,  78,   0,  96, 100,  42,   0,   0, 174,  36,  88,
         0,   0, 151,  64, 169,   0,   0,  11,  20, 191,   0,   0],
      dtype=int32)

In [73]:
array.sort(axis = 0)

In [74]:
array

array([[ 38,  55,  67,  69],
       [ 89,  97, 110, 112],
       [122, 139, 151, 156],
       [137, 151, 183, 188]], dtype=int32)

# Stacking

In [77]:
# Generate random arrays
ss_arr_1 = np.random.randint(10, size=(2, 2))
print("ss_arr_1\n", ss_arr_1)
ss_arr_2 = np.random.randint(10, size=(2, 2))
print("ss_arr_2\n", ss_arr_2)

ss_arr_1
 [[7 6]
 [6 3]]
ss_arr_2
 [[2 0]
 [8 4]]


In [80]:
np.vstack((ss_arr_1,ss_arr_2))
np.hstack((ss_arr_1,ss_arr_2))

array([[7, 6, 2, 0],
       [6, 3, 8, 4]], dtype=int32)

In [85]:
ss_arr_3 = np.delete(array,1,axis = 0)

In [94]:
ss_arr_4 = np.arange(20)

In [119]:
ss_arr_4.resize((10,2))

In [120]:
ss_arr_4

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [132]:
np.vsplit(ss_arr_4,5)

[array([[0, 1],
        [2, 3]]),
 array([[4, 5],
        [6, 7]]),
 array([[ 8,  9],
        [10, 11]]),
 array([[12, 13],
        [14, 15]]),
 array([[16, 17],
        [18, 19]])]

In [143]:
array.cumsum()

array([  38,   93,  160,  229,  318,  415,  525,  637,  759,  898, 1049,
       1205, 1342, 1493, 1676, 1864])

In [144]:
array.sum()

np.int64(1864)

In [158]:
array

array([[195, 171,  25, 149],
       [ 73, 125,  60, 115],
       [ 23,  48,  72,  24],
       [ 23, 101, 192,  20]], dtype=int32)

In [161]:
print(array.min(axis = 1))
print(array.argmin(axis=1))
array[array.argmin(axis=1), range(array.shape[1])]

[25 60 23 20]
[2 2 0 3]


array([23, 48, 25, 20], dtype=int32)

In [157]:
print(array.max(axis = 1))
print(array.argmax(axis=1))

[195 125  72 192]
[0 1 2 2]


In [148]:
np.gcd.reduce([9, 12, 15])

np.int64(3)

In [149]:
np.lcm.reduce([9, 12, 15])

np.int64(180)